version: "3.5"

services:
  db:
    image: postgres:12.1
    container_name: go_google_scraper_db
    environment:
      - POSTGRES_DB=go_google_scraper_development
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
