name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - master
      - development
    types:
      - completed
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_USERNAME: ${{ github.repository_owner }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Branch Tag
        uses: nimblehq/branch-tag-action@v1.2
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Set HEROKU_APP
        run: |
          if [[ $BRANCH_TAG = "latest" ]]
          then
            echo "HEROKU_APP=go-google-scraper" >> $GITHUB_ENV
          else
            echo "HEROKU_APP=go-google-scraper-staging" >> $GITHUB_ENV
          fi

      - name: Docker Login
        uses: docker/login-action@v1.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        run: |
          docker-compose pull || true
          docker-compose build
          docker-compose push app

      - name: Heroku login
        run: heroku container:login
  
      - name: Heroku release
        run: |
          heroku container:push --arg DOCKER_REGISTRY=$DOCKER_REGISTRY,DOCKER_IMAGE=$DOCKER_IMAGE,BRANCH_TAG=$BRANCH_TAG --recursive
          heroku container:release web worker
