name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.x

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Setup database
        run: make test-env-setup

      - name: Tests
        run: make test

      - name: Destroy database
        run: make test-env-destroy
